20 能力値クラス実装
CASru-GAME/TeamGameDevBootcamp pull request #24
Opened 2024-07-19 16:44 UTC by momomo546

2024-07-19 16:47 UTC, dugite-git commented on Assets/App/Data/Parameters/Hp.cs
> +    public Hp(int maxHpValue) : this(maxHpValue, maxHpValue)
ここの記法ってなんです？

2024-07-19 16:48 UTC, dugite-git commented on Assets/App/Data/Parameters/Hp.cs
> +    public Hp(int maxHpValue) : this(maxHpValue, maxHpValue)
`public Hp(int maxHpValue) : this(maxHpValue, maxHpValue)`

2024-07-19 16:55 UTC, momomo546 commented on Assets/App/Data/Parameters/Hp.cs
> +    public Hp(int maxHpValue) : this(maxHpValue, maxHpValue)
`this(maxHpValue, maxHpValue)`　この部分で上の引数２つのコンストラクタを使用するみたいです。  
`public Hp(int maxHpValue) : this(maxHpValue, maxHpValue)`の｛｝内が不要みたいなので修正します。

2024-07-19 17:03 UTC, AiletS commented on Assets/App/Data/Parameters/Hp.cs
> +
ここ今はcurrentHpだけ変更されるんですけど、maxHpも変更されるようにするのはどうでしょうか。レベルアップするとmaxHpもあがるんで
```csharp
        this._maxHp += addedHp.maxHp;
        if (this._currentHp + addedHp.maxHp > this._maxHp) {
            return new Hp(this._maxHp, this._maxHp);
        }
        else {
            return new Hp(this._maxHp, this._maxHp + addedHp.maxHp);
        }
```

2024-07-19 17:05 UTC, AiletS requested changes

2024-07-19 17:05 UTC, AiletS commented on Assets/App/Data/Parameters/Hp.cs
> +    public Hp(int maxHpValue) : this(maxHpValue, maxHpValue){}
これ初めて見る人はわかりにくいと思うのでコメントで説明お願いします

2024-07-19 17:05 UTC, AiletS commented on Assets/App/Data/Parameters/Hp.cs
> +
ここ今はcurrentHpだけ変更されるんですけど、maxHpも変更されるようにするのはどうでしょうか。レベルアップするとmaxHpもあがるんで
```csharp
        if (this._currentHp + addedHp.maxHp > this._maxHp + addedHp.maxHp) {
            return new Hp(this._maxHp + addedHp.maxHp);
        }
        else {
            return new Hp(this._maxHp + addedHp.maxHp, this._maxHp + addedHp.maxHp);
        }
```

Mpの方も同じようにどうですか

2024-07-19 17:08 UTC, dugite-git requested changes

2024-07-19 17:08 UTC, dugite-git commented on Assets/App/Data/Parameters/Hp.cs
> +            return new Hp(this._maxHp, this._maxHp + addedHp.maxHp);
ここ間違ってません？？？
`return new Hp(this._maxHp, this._maxHp + addedHp.maxHp);`

2024-07-19 17:08 UTC, dugite-git commented on Assets/App/Data/Parameters/Mp.cs
> +            return new Mp(this._maxMp, this._maxMp + addedMp.maxMp);
ここも間違ってません？？？
`return new Mp(this._maxMp, this._maxMp + addedMp.maxMp);`

2024-07-19 17:09 UTC, AiletS requested changes
コンストラクタで引数が一つのやつと２つのやつがどんな時に分けて使われるかコメントで説明お願いします。

それと、AddとSubstractにDebug.Logでどのくらい足されたか引かれたか書くのがいいと思います。

2024-07-19 17:10 UTC, momomo546 commented on Assets/App/Data/Parameters/Hp.cs
> +            return new Hp(this._maxHp, this._maxHp + addedHp.maxHp);
すいやせん……

2024-07-19 17:15 UTC, momomo546 commented on Assets/App/Data/Parameters/Hp.cs
> +    public Hp(int maxHpValue) : this(maxHpValue, maxHpValue){}
//引数が１個の場合、this(maxHpValue, maxHpValue)の部分で上のコンストラクタを使用し、
//同じ値をcurrentHpとmaxHpに代入している。
というコメント追加しようと思いますがどうでしょうか？

2024-07-19 17:15 UTC, momomo546 commented on Assets/App/Data/Parameters/Mp.cs
> +            return new Mp(this._maxMp, this._maxMp + addedMp.maxMp);
すいやせん……修正します……

2024-07-19 17:24 UTC, AiletS commented on Assets/App/Data/Parameters/Hp.cs
> +    public Hp(int maxHpValue) : this(maxHpValue, maxHpValue){}
いいと思います

2024-07-19 17:30 UTC, AiletS submitted a review, later dismissed
今はこれでいいと思います！

2024-07-19 17:31 UTC, dugite-git approved these changes
OK！！！

2024-07-19 18:04 UTC, Elise3993 requested changes
`Request changes`のテストのためのレビュー

2024-07-19 19:09 UTC, Elise3993 reviewed
全部確認してレビューしました～
かなり細かいことまでレビュー出さしてもらったので確認していただけると嬉しいです

2024-07-19 19:09 UTC, Elise3993 commented on Assets/App/Data/Parameters/Hp.cs
> +    }
レベルアップ時に、「HPの最大値が増える＆全回復」という仕様で定まった話は効いたのですが、「最大HPをちょっとだけ増やす」みたいなアイテム使ったときに流石に全回復するのは変ですし、最大HP上げる関数は分けた方がいいですね
それでレベルアップ時とかの「HPの最大値が増える＆全回復」は「HPの最大値が増える」関数と「全回復」関数を両方実行するみたいに実装することになると思います

あと、もしこのまま`return new Hp(this._maxHp + addedHp.maxHp);`の処理のままで実装するにしても、`AddMaxHp`という名前からは推測できない全回復の文脈が入ってしまっているので`AddMaxHpAndFullRecovery`とかに名前変える方がいい気がしました

2024-07-19 19:09 UTC, Elise3993 commented on Assets/App/Data/Parameters/Hp.cs
> +using System;
名前空間を考慮してみるといいかもです

2024-07-19 19:09 UTC, Elise3993 commented on Assets/App/Data/Parameters/Hp.cs
> +        if (this._currentHp + addedHp.maxHp > this._maxHp)
addedHpって「現在のHP」と「最大HP」っていう情報がいらないと思うので、確かにHPのやりとりではあるんですが`addedHp.maxHp`となってしまっているのが気になりました

2024-07-19 19:09 UTC, Elise3993 commented on Assets/App/Data/Parameters/Mp.cs
ちゃんとは確認していませんが、HpをMpに置き換えた同様の処理だと思うので、Hpで指摘した部分をMpでも適用してもらえるとありがたいです

2024-07-19 19:11 UTC, AiletS commented on Assets/App/Data/Parameters/Hp.cs
> +            throw new ArgumentException("Value cannot be negative");
https://docs.unity3d.com/ja/2021.1/ScriptReference/Assertions.Assert.html
これを参考にどうぞ

2024-07-19 19:12 UTC, AiletS commented on Assets/App/Data/Parameters/Hp.cs
> +using System;
namespace App.Dataでいいと思います

2024-07-19 19:14 UTC, AiletS commented on Assets/App/Data/Parameters/Hp.cs
> +        if (this._currentHp + addedHp.maxHp > this._maxHp)
確かにこれ名前のせいで非常に紛らわしいので他の方法を検討するのがいいかもしれません

2024-07-20 04:00 UTC, momomo546 commented on Assets/App/Data/Parameters/Hp.cs
> +    }
分割します

2024-07-20 04:00 UTC, momomo546 commented on Assets/App/Data/Parameters/Hp.cs
> +using System;
追加します

2024-07-20 04:30 UTC, momomo546 commented
案として
- `value`をフィールド変数に追加し、maxHpと同じになるように初期化
- `AddMaxHp`を`maxHp`だけを上げるように変更
- 引数2つのコンストラクタを`private`にして`currentHp`をメソッドからしか変更できないようにする
- namespaceの追加

しようと思ってます。  
一つ目の`value`はメソッドの計算で使います。 
 
三つめの理由は
- コンストラクタが2つ使えるのは分かりにくい。
- 実際に使うときに`currentHp`と`maxHp`に異なる値を入れて生成する機会がない。
- 自由に`currentHp`と`maxHp`の異なる`Hp`クラスを作れると外部で`AddCurrentHp`や`AddMaxHp`メソッドが作れてしまう。

2024-07-20 07:48 UTC, Motoki4472 submitted a review, later dismissed

2024-07-20 11:34 UTC, dugite-git approved these changes
良いと思います！！！

2024-07-20 22:16 UTC, AiletS requested changes
`Mp`だけ修正したらいいと思います
それとデバッグ用のスクリプトみればわかるんですけど書き方ちょっとだるくないですか？
本当にこれでいいんですかね？

2024-07-20 22:19 UTC, Elise3993 commented
↑のコミットでHPに関してテストスクリプトの実装・バグ修正を行いました。MPに関してはノータッチなので修正よろしくお願いします。あとテスト用スクリプトの↑の方にお気持ちコメント入っちゃったのでそれも修正してもらえると助かります（すいません）

あと、多分改行の方法の環境による差が混じってしまったみたいです。めっちゃ申し訳ないんですがこの辺り調べて揃えてもらえるとありがたいです。（自分も調べます）
![image](https://github.com/user-attachments/assets/adcfb5fb-21f8-44bc-ae23-3dbc5dfc8211)

2024-07-20 22:22 UTC, Elise3993 commented
HPのテストスクリプトを書いている途中で感じたのですが、関数実行のために新しくHPインスタンスを作るのがすごく凡長に感じました。確かに値オブジェクトとしてはこの書き方が正しいとは思うのですが、少々変な感じがしました。（感想ですが）

https://github.com/CASru-GAME/TeamGameDevBootcamp/blob/994e41817197131fc0f81b8f48669da97e1b6e69/Assets/App/Data/Parameters/TestHp.cs#L63-L84

2024-07-20 22:27 UTC, Elise3993 commented
あと、`private Hp(int maxHp, int currentHp) `の引数の位置を逆にしたく思いました。
表記としては `currentHp / maxHp (50 / 80)` みたいなイメージがあるので不自然に思いました

https://github.com/CASru-GAME/TeamGameDevBootcamp/blob/994e41817197131fc0f81b8f48669da97e1b6e69/Assets/App/Data/Parameters/Hp.cs#L23-L24

2024-07-21 12:28 UTC, AiletS submitted a review, later dismissed
Mpだけ直したらいいと思います

2024-07-21 15:13 UTC, AiletS approved these changes
LGTM!!!

2024-07-21 15:13 UTC, dugite-git approved these changes
一旦マージしましょう

2024-07-21 15:15 UTC, merged