経験値クラス作った
CASru-GAME/TeamGameDevBootcamp pull request #48
Opened 2024-07-27 16:58 UTC by ujisuke

2024-07-27 17:24 UTC, dugite-git submitted a review, later dismissed

2024-07-28 12:05 UTC, AiletS requested changes
すべてのコンストラクタをpublicにしてください

2024-07-28 13:47 UTC, AiletS approved these changes
LGTM!

2024-07-28 13:47 UTC, dugite-git approved these changes
LGTM！

2024-07-28 14:00 UTC, merged