#58 battleシーンのstateつくる
CASru-GAME/TeamGameDevBootcamp pull request #61
Opened 2024-08-09 14:33 UTC by ujisuke

Battleシーンでのコマンド選択の状態遷移を全部つくりました

2024-08-12 05:30 UTC, AiletS requested changes
`BattleDebug~~~StatePresenter` と `BattleDebug~~~StateUseCase `ですべての状態でスクリプトを分けていますが、全部１個でまとめていいと思いますよ。

`BattleDebugStatePresenter` と `BattleDebugStateUseCase` とかにですね
もちろん Presenterには複数のボタンが含まれることになるし、UseCase にも Initializeがでかくなります

2024-08-12 05:30 UTC, AiletS commented on Assets/App/Scripts/Battle/Usecases/BattleStateMachineUseCase.cs
> +        private BattleStateMachinePresenter _battleStateMachinePresenter = new BattleStateMachinePresenter();
ここ new じゃなくて VContainer から Inject するのではないですか？

2024-08-14 12:16 UTC, ujisuke commented
1.BattleDebugStatePresenterとBattleDebugStateUseCaseを新規に作成し、各状態のスクリプトをまとめました
2.new→Injectに変更しました

2024-08-23 14:23 UTC, AiletS approved these changes
LGTM!!!

2024-08-29 14:07 UTC, dugite-git approved these changes

2024-08-29 14:15 UTC, merged